language: python
python:
  - "3.6" 
  - "3.7"
  - "3.8"
  - "3.8-dev" 
  - "nightly"

install:
  - python3 setup.py install

script:
  - git-php-lint -v
  - python3 -m unittest gitphplint/tests/*.py 
